_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
                - 83
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
                - 83
                - 98
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.18.7
            "6": 4.46.3
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batchid:
    value: 1
batchimage:
    value: 2
batchtest:
    value: 8
clip_embeddings_dim:
    value: 4
data_path:
    value: /workspace/data/changhyun/dataset/danbooru_safe/
epoch:
    value: 2
extractor_weight:
    value: /workspace/data/changhyun/output/global_adapter/256/extractor/model_2000.pt
freeze:
    value: false
image_adapter_weight:
    value: None
lr:
    value: 0.0002
lr_scheduler:
    value:
        - 320
        - 380
mode:
    value: train
optimizer:
    value: adamw
output_dir:
    value: /workspace/data/changhyun/output/sd_image_adapter_cfg_4_768_ip_euler_zero_adapter
query_image:
    value: /workspace/dataset/top15character/Elric Edward/Image_2.jpg
weight_decay:
    value: 0.0001
